appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: r2PVTKKQUi8xvnS1xVn2R68C9jWHmOQAx8rc7j0P+GwoppReDC5Z6Unsp3t1mdr3KWcpoHzoY9z6PVR7XDoHqjV4o8NSrUUgcJJx6NnhFIqEUxEJ1+n5N4ieYuL77WGmanxLcw6kwTEtTCQGuUibyVomFUlUtLF2koMgvYmk/QKp36BTAuOR6I1fQQGzYQCuA7l2WZhjlOyGp3Knnu44cmvVLKn+rx+C0pgqOU1NzZKh4uY08atputh3hAW5kCi/SbOHzuF9dSOT23jUSaNpG8mVXUR2USB+7q8v6RFGNPGpmDl55cNSP3ruuhyJtIXed8Rq6j9wQ+BcfWZUvlZR3vUX16wP+lY/U9/1+kfCh4g14oqAiYB8brqcDNNWldv4/qhdnXVu9Y9kV6x0o/wOg1yUDuacAPIKdjAySvliBu1tyz+P2QycjntD1ZT3BzjouuPYN9bOLm4bc1kGcTaFuHB7Bdabk/emPyk+s9E140P9d9jQvdfO+Hk82cY84y7O1i6YPUgiNVSQ60LN6ey/nGuc/YzDQMdKuw2zbBargfeCx9DapUqy94yW/33AWGpp36Ef7vVGZYkvTpkGQW7rb9MYomFFEOWhnSLw1KtZHZ/P5ZSA6kZuELWEuXFtcqOcuZ4fPT57JdSalPeu/ZqzvNwn7qkLpGuRWIFsvN4THas=
